name: 1. Actualizar M3U
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python update_m3u.py
    
    - name: Subir cambios
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lista.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update M3U" && git push)
        
    - name: Limpiar workflows viejos (mantener 3)
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh run list --workflow "1. Actualizar M3U" --limit 100 --json databaseId -q '.[3:][].databaseId' | xargs -I{} gh run delete "{}" || true
